export type ThemeStyle = 'dynamic' | 'classic'
export type LayoutMode = 'vertical' | 'horizontal' | 'mix'
export type UserActionsPosition = 'header' | 'sidebar'
export type LogoPosition = 'header' | 'sidebar'
export type MenuPosition = 'header' | 'sidebar'
export type ThemeMode = 'light' | 'dark' | 'system' 